//CREATED BY li jiatong on 2022 oct 16 
#include "x86_desc.h"

extern void fill_idt_entries();
enum IDT_VECTORS_FIRST_20{
    DIVIDE_ERROR_EXC, //0
    DEBUG_EXC,
    NMI_INTERRUPT,
    BREAKPOINT_EXC,
    OVERFLOW_EXC,
    BOUND_RANGE_EXCEEDED_EXC, //5
    INVALID_OPCODE_EXC,
    DEVICE_NOT_AVAILABLE_EXC,
    DOUBLE_FAULT_EXC,
    COPROCESSOR_SEGMENT_OVERRUN,
    INVALID_TSS_EXC, //10
    SEGMENT_NOT_PRESENT,
    STACK_FAULT_EXCEPTION,
    GENERAL_PROTECTION_EXC,
    PAGE_FAULT_EXC,
    PRESERVED, //15 is preserved in intel manual
    X87_FPU_FLOATING_POINT_ERROR,
    ALIGNMENT_CHECK_EXC,
    MACHINE_CHECK_EXC,
    SIMD_FLOATING_POINT_EXC//19
};