boot.o: boot.S multiboot.h x86_desc.h types.h
intr_wrapper.o: intr_wrapper.S intr_wrapper.h
syscall_handler.o: syscall_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
cursor.o: cursor.c cursor.h lib.h types.h
execute.o: execute.c lib.h types.h execute.h syscall.h filesystem.h \
  page.h terminal.h rtc.h x86_desc.h syscall_handler.h
filesystem.o: filesystem.c filesystem.h types.h lib.h execute.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h keyboard.h rtc.h \
  syscall_handler.h syscall.h execute.h pit.h intr_wrapper.h
kernel.o: kernel.c multiboot.h types.h lib.h x86_desc.h i8259.h debug.h \
  tests.h idt.h keyboard.h page.h rtc.h terminal.h filesystem.h \
  syscall_handler.h syscall.h execute.h cursor.h pit.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h terminal.h \
  execute.h page.h
lib.o: lib.c lib.h types.h execute.h terminal.h
page.o: page.c page.h lib.h types.h x86_desc.h
pit.o: pit.c pit.h lib.h types.h i8259.h execute.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h execute.h
syscall.o: syscall.c lib.h types.h syscall.h x86_desc.h terminal.h rtc.h \
  filesystem.h execute.h page.h
terminal.o: terminal.c lib.h types.h keyboard.h terminal.h page.h \
  execute.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h terminal.h \
  keyboard.h filesystem.h
